vim-jp/slacklog-generator

- _config.yml
slacklog_data は 変換元のソースだから jekyll の対象ではないはずです。
tmp/ は .gitignore に記載されてる適当なファイル置き場なのでやはり jekyll の対象ではありません。
なので両方とも jekyll の `exclude` に追加しました。
for #24
> exclude `slacklog_data/` and `tmp/` from jekyll build

- Makefile
- README.md
- scripts/docker.sh
`log-data` ブランチが別リポジトリになったため、取得方法を変更する。
> Update setup step of getting log-data

- scripts/lib/generator.go
- slacklog_template/channel_index.tmpl
- slacklog_template/channel_per_month_index.tmpl
- slacklog_template/index.tmpl
こうするとテンプレートの表記方法を統一できそう
表記を統一できると syntax が適用できるようになって
フロント側の負荷が軽減するはず。
> unite template notifications to `{{ ... }}` 

- .github/workflows/build_pages.yml
今までは以下のようになっていた。
1. `slacklog-generator` の `master` ブランチが更新
2. GitHub Actions が走り、`slacklog` 側に `rebuild` タグを push
3. タグの push を契機に `slacklog` 側で GitHub Actions が走り、新しい `gh-pages` を push
しかしこれは回りくどいので、ビルドして新しい gh-pages を push するところまで `slacklog-generator` 側で行う。
> html のビルドを slacklog-generator 側の Actions で行う

- scripts/lib/emoji.go
- scripts/lib/store.go
`EmojiTable` のフィールド名が実態に合っていなかったので `URLMap` から `ExtMap` に修正
> Fix the field name of EmojiTable

- scripts/lib/generator.go
- scripts/lib/time.go
- slacklog_template/channel_per_month_index.tmpl
for https://github.com/vim-jp/slacklog-generator/issues/28
thread 内の時刻が `2日 15:04:05` の表記のため
月を跨ぐほどの遅い返信だと違和感が強いのを修正した。
具体的にはスレッド自身の時刻 (`.ThreadTs`) とスレッド内メッセージの時刻 (`.Ts`) の差から
以下の4つのケースに分けて異なるフォーマットを使用した。
1. 年が違う - `2006年1月2日 15:04:05`
2. 月が違う - `1月2日 15:04:05`
3. 日が違う - `2日 15:04:05`
4. 年月日が同じ - `15:04:05`
合わせて「最終返信」の表記もこのフォーマットに修正した。
この結果以下のような表示になる。
(なおこのデータはもともと当日のレスポンスだったものに、同月10日後の返信と、月を跨いだ返信を無理矢理加えたものから生成した)
> change resolution of time of messages in thread

- scripts/lib/generator.go
- scripts/lib/message.go
- scripts/lib/store.go
- scripts/lib/thread.go
`Message` をポインタで取り扱うようにしました。これは #36 で指摘・依頼されたようにツール側で `Message` 以下の情報を埋める場合に値のままだと非効率&バグの温床になるのを事前に防ぎます。
(例: メッセージ側には情報が入ってるがスレッドには入ってないなどなど)
その結果として以下のことが起こっています。
* `Messages` (`[]*Message`)  の定義
* `Sort()` メソッドを生やした & 使ってる場所の見通しが良くなった
* `MessagesMap` (`map[MessageMonthKey]Messages`) の定義
* `Keys()` メソッドを生やした & 使ってる場所の見通しが良くなった
* `Thread` 関連
* `Put()` を生やした & 使ってる場所の見通しが良くなった
* レシーバの名前を `t` から `th` へ変更した。 `t` のままテストを書き始めるとめんどいことになるので
* いくつかのループからインデックスが消え、インデックスを使った参照が消え見通しが良くなった
> treat message by pointer

- .github/workflows/ci.yml
- README.md
- scripts/pages_diff.sh
- scripts/site_diff.sh
fix #11 
Actions で pages\_diff.sh と site\_diff.sh を走らせてその結果(差分)をArtifactsにアップするようにしました。
上の Checks タブから確認してみてください。
1. Pull Request の <b>Checks</b> タブを開く
2. <b>CI</b> ワークフロー(右側)を選択
3. <b>Compare Pages and Site</b> ジョブ(右側)を選択
4. <b>Artifacts</b> ドロワー(左側)を選択
5. `diffs-{数値}` アーティファクトをダウンロード
> generate diffs on CI

- .github/workflows/build_pages.yml
- scripts/lib/generator.go
- slacklog_template/channel_index.tmpl
- slacklog_template/channel_per_month_index.tmpl
- slacklog_template/index.tmpl
GoでHTMLを生成している部分からjekyllの`site.baseurl`を取り除きました。
baseurl部分はgenerateコマンドを呼ぶ時に環境変数`BASEURL`で渡す形にしています
- `converter.go`の方は取り除いていません
- ~~現状テストデータが手元になく、どのような仕様なのかが分からないため~~
- 僕の勘違いでしたが、直すの難しそうなので一旦保留でお願いします
- テスト環境でトップレベルへの遷移がバグってたので、何も指定していない時のbaseurlを`/`にしていますが、問題があれば戻します
> Don't use jekyll's baseurl at generator

- scripts/build.sh
- scripts/site_diff.sh
脱Jekyllの最終チェックのため、site_diff内で新しい差分と古い差分に別のビルドスクリプトを適用するように変更
> Change site_diff script for last step

- scripts/lib/downloader.go
- scripts/lib/downloader_test.go
- scripts/lib/main_test.go
- scripts/lib/message.go
#22 での残件に対応しました。やったことは以下の3つです。
* 大きくなり得る&先頭以外使ってない `errs []errors` の代わりに `firstError error` にした
* テストの安定化
* システムが提供するテンポラリディレクトリを使うように
* Windowsでも実行できるように (開いたままのファイルを clean up してた)
* readAllMessages についてのコメントを修正: 先に一般的な説明をしてから特殊なケースの説明をするように
> Extra works for Downloader

- internal/slacklog/message.go
Jekyll たんが publish してくれないのでしかたなく名前を変えていた一部の files のファイル名を変えないようにします。
既存の `slacklog` リポジトリの `log-data` ブランチ内のファイルの更新が必要になります。ビルドとかは問題ないけど、直すまではリンク切れが発生します (ほんのごく一部のファイルです)。
> Remove workaround for jekyll

- internal/slacklog/message.go
一見不要に見えるソートがどうして必要なのかをコメントに書いといた。
でないとふとしたはずみで消しそうになる。
> write comment why ReadLogFile called in sorted

- go.mod
- go.sum
- internal/slacklog/message.go
- internal/slacklog/message_test.go
- internal/slacklog/ts.go
- internal/slacklog/ts_test.go
【悲報】attachment の `"ts"` は数値の場合がある…。
> Fix type of MessageAttachment.Ts

- internal/slacklog/message.go
空の月でも html ページが生成されてしまっているようだったのでたぶん修正。
> Skip invisible data

- scripts/build.sh
preparation for merging #78
#78 では _logdata にデータを集約させてるんですが、build.sh が対応してないため merge-base がビルドできなくなってしまうのをこの修正で対応します。
> use _logdata for emojis and files if available

- .github/workflows/build_pages.yml
- .github/workflows/ci.yml
- .gitignore
- Makefile
- README.md
- scripts/build.sh
- scripts/download_emoji.sh
- scripts/download_files.sh
- scripts/generate_html.sh
- scripts/site_diff.sh
fix #78 
ログ(slacklogレポジトリのlog-dataブランチ)の展開を
プロジェクトルートではなく `_logdata/` 下で行う PR です。
この変更を適用後に `make logdata` することでログを展開できます。
展開後の古いログ emojis/ files/ そして slacklog_data/ は手動で消してください。
また `_logdata/` 下を壊してしまった場合には `make logdata-restore` でローカルキャッシュからログを再展開します。
最新のログを取得して展開するには `make logdata-update` です。
> Quarantine logdata

- templates/channel_index.tmpl
- templates/channel_per_month_index.tmpl
- templates/index.tmpl
fix #50 
各ページへのリンクから index.html を省略した。
合わせて canonical からも index.html を消した。
これで正式なURLは全部 index.html 抜きで、 `/` で終わることとなる。
> omit "index.html" from URL

- internal/slacklog/message.go
- subcmd/download_files.go
- templates/channel_per_month_index.tmpl
message に添付されている files の中には、slack.com へアップロードされていない、外部へのリンクが含まれる場合があることが判明しました。
そこで、
1. message.upload フラグが立っていないものはダウンロードしない
このフラグは今のところ、
- gist.github.com へのリンク (新規で作成する方法が不明…昔だけの仕様の可能性あり)
- すでにアップロード済みのファイルの2回目以降の投稿
で確認されています。
message 側についているフラグなのが気になるところ…複数のファイルの一部だけがアップロードされた場合にどうなるのか不明。
2. ダウンロードしなかったファイルへの html での参照はただのリンクにする
2回目以降の投稿の件があるため、この判定は message.upload フラグではできません。
仕方ないのでファイルの元の場所のドメインからふんわり判定することにします。
> Skip downloading not uploaded files

- templates/channel_per_month_index.tmpl
#76 で歴史改変に失敗したため、prismjs のロードタグが消失してました。
> Add prismjs loading

- internal/slacklog/generator.go
#76 の後始末です `filepath.Join` を使うように修正しました
> Fix generateFileHTML to use filepath.Join

- .github/workflows/ci.yml
- scripts/site_diff.sh
fix #97
* ci.yml で呼び出すときの `-d` オプションを削除した
* 外部コマンド (generate-html & scripts/build.sh) が失敗したときにそのログを出力するようにした
> improve site_diff.sh

- internal/slacklog/json.go
- internal/slacklog/user.go
fix #69 
将来のフィールドの追加を見逃さないためにチェックをONにした。
結果 users.json に5つの未知のフィールドがあることがわかった。
> raise an error for uknown properties in JSON

- scripts/site_diff.sh
そろそろ site_diff で空白を無視してよい頃合いかなと。
またテンプレートの分離 (#21) をやるうえで、
たぶん事前にこれがあったほうが良いから。
> make site_diff.sh ignore whites

- internal/slacklog/generator.go
- internal/slacklog/message.go
botのアイコンが表示されないケースがあったので修正
ついでにGetUserの部分を外に出して変数のokをuserFoundに変更していますが、問題があれば指摘をお願いします。
> Fix case of bot icons are invisible

- subcmd/serve/serve.go
- subcmd/subcmd.go
開発用に特殊なファイルサーバを作りました。
以下のコマンドで起動できます。
```console
$ go build
$ ./slacklog-generator serve
```
普通に _site/ 下をサーブするのですが `/files/` と `/emojis/` は
https://vim-jp.org/slacklog/ をリバースプロキシします。
つまり _site/files/ と _site/emojis/ を _logdata からコピーする必要がなくなります。
ポートはデフォでは `:8001` で開いてますが `-addr` オプションで指定もできます。
> add "serve" sub-command

- templates/channel_per_month/attachment.tmpl
- templates/channel_per_month/index.tmpl
- templates/index.tmpl
外部サイトへは `target="_blank" rel="noopener noreferrer"` を付与した。
あとトップページのリンクもモバイルのファーストビューを 2 行消費するのは勿体無いのでシンプルに。
> Add target="_blank" to other site

- internal/jsonwriter/jsonwriter.go
- internal/slackadapter/common.go
- internal/slackadapter/conversations_history.go
- internal/slackadapter/cursor_iter.go
- main.go
- subcmd/fetchmessages/fetchmessages.go
KoRoNさんが途中まで書き上げていたfetch-messagesのPR
https://github.com/vim-jp/slacklog-generator/pull/116
を引き継ぐ形で実装してみました。
internal/slackadapterの実装方針の理解があっているかどうかに少し不安が。
（動くのでリファクタリングレベルでの話である） 
- 責務は「使いやすい param / response で公式ライブラリをラップ」
- 使いにくい定義のWrap
- timestamp string <=> *time.Time 
- Cursor 処理の隠蔽
- やや冗長な書き味の箇所が含まれるので、もう少しSmartな定義にしたかったかも
- internal/slackadapter/conversations_history.go#L33-38とか
- クライアントの生成も各関数の中で実施する
- slack.Newを裸でそのまま各関数に書かせるのは少しリスクかも
- NewしたClientを持ち回すのとどっちが良いかは見えていない
```console
$ go run . fetch-messages --data-dir ./_logdata/slacklog_data --date 2020-07-05 --verbose
```
> Implement fetch-messages

- internal/slackadapter/common.go
- internal/slackadapter/conversations.go
- main.go
- subcmd/fetchchannels/fetchchannels.go
channel一覧を取得する fetch-channels subcommand の実装
一応自分専用のWorkspaceでfetch-channels -> fetch-messagesを呼び出して、
全履歴を確認できたので、動作確認はできています。
- refactor: インターフェイスをConversationsHistoryとどこまで揃えるかちょっと悩む
- OK fieldいっそ捨てるか: Goのライブラリが隠蔽しているAPIがあった
- HasMoreもういっそ捨てるか
- APIによっては帰ってこないし、slackadaptor.XXXResponseに直にCursor生やしてしまっても良さそう
> implement 'fetch-channels'

- internal/jsonwriter/jsonwriter.go
ファイルをつくるものの、中身がないときにnullになってしまっていたので修正。
`[]` を出力することも考えたが、ファイル数が増えるだけで良いことないはずなのでそもそも作らない対応。
> 結果が空の場合、nullを出力せずファイルを作らない

- internal/slacklog/message.go
- subcmd/fetchmessages/fetchmessages.go
Messages in threads cannot be fetch by `conversations.history` API, but can `conversations.replies`.
We need call it.
> Fetch thread messages

- internal/slacklog/slack.go
- subcmd/download_files.go
- Fixed a bug: When the file extension of filename and the file extension of URL are different, filename of downloaded file may be wrong.
- This may occur for videos (filename is `a.mp4` and name of thumbnail file is `a.jpeg`).
- Now, downloads thumbnail of videos.
> Download thumbnail of videos

- templates/channel_index.tmpl
- templates/channel_per_month/index.tmpl
- templates/index.tmpl
A numeric character reference must be ended with `;`.
Fix missing semicolons.
(not sure if `#` needs to be use numeric character references.)
> Fix numeric character references

- internal/slacklog/thread.go
`invalid memory address or nil pointer dereference` occurs when root message is deleted.
> Fix the case thread root is deleted

- subcmd/download_files.go
GitHubにプッシュするために100MiB以上のファイルを雑に切り捨てるパッチです
> Fix push to GitHub fails caused by download-files

- internal/slacklog/generator.go
昔の発言から探すよりも最近の発言を他で紹介したいと思うことの方が多いので、新しい方を上に変更。
> Move recent log links up
