vim-jp/slacklog-generator

- scripts/lib/emoji.go
- scripts/lib/store.go
ref: #31 
コメントで指摘いただいた部分の修正
* フィールド名の変更
* コメント位置の移動
// コメント位置は他にもなおすところがあるが、それは別 PR にする
> Rename the field name and move comment

- scripts/lib/generator.go
> Eliminate global variable

- scripts/build.sh
- scripts/site_diff.sh
* use single generate_site func
* stop to log in ./scripts/build.sh
> refactoring script

- scripts/lib/message.go
実際に API でデータを取ってきたりして、足りてなさそうなフィールドを見繕って追加しました。
何かのリファレンスに従ったなどではなく、完全に手作業です。網羅性はありません。
そもそも Slack の API はリファレンスに書かれていないフィールドを平気で返して来るので何も信用できない…。
> Add more fields to structs

- scripts/lib/generator.go
jekyllThrough使われてないみたいなので消しました
> Remove jekyllThrough

- README.md
> Fix specify _site directory

- slacklog_template/channel_index.tmpl
- slacklog_template/channel_per_month_index.tmpl
- slacklog_template/index.tmpl
https://github.com/vim-jp/slacklog-generator/issues/48
差分大きいけどインデントずらしただけで DOM の構成には手を入れてないです。
> Fix indent

- .gitignore
- Makefile
- scripts/build.sh
- scripts/generate_html.sh
Directly generate pages to _site, Fix #66
> Don't generate slacklog_pages

- internal/slacklog/generator.go
チャンネルの index ページ内の年月の並びのソート処理が間違っていたのを修正しました。
> Fix sort of channel index

- .github/workflows/build_pages.yml
> resurrect gh-pages update

- .github/workflows/build_pages.yml
> "cd" before push to gh-pages branch)

- internal/slacklog/downloader.go
ファイルのダウンロード時、token が無効等の理由で認証が通っていない場合にログインページ(200)にリダイレクトされてしまうため、リダイレクト = エラーとして扱っていたが、なぜか .svg ファイルをダウンロードする際にも正常なリダイレクトが発生することが判明しました。
参考: https://gist.github.com/thinca/c2156a848f2038fd8f250e7d3e3894da
仕方ないので、リダイレクト先の URL を見て、たぶん認証ページに飛んでそう、というやつだけをエラーにするようにしてみました。サンプルが少ないのでこれで正しく判別できるかは不明ですが、ひとまず現段階のログの範囲では正しく処理できていそうです。
> Fix detection way of auth error while downloading

- .github/workflows/build_pages.yml
- internal/slacklog/generator.go
- internal/slacklog/message.go
- scripts/generate_html.sh
- scripts/site_diff.sh
- subcmd/generate_html.go
- templates/channel_per_month_index.tmpl
Close #54
Prismjs使いました カラースキームは tomorrow にしてあります。
> Add text/plain with syntax highlighting

- internal/slacklog/message.go
fix #45 
* make isVisible private
他で使ってないので非公開にしました。
本来ならconverterなりgeneratorが出力時に使うべきなんですが
現在は message を読み込むときのフィルタリングに使ってます。
なのでそれらの設計を修正するときまで非公開としましょう。
* add isTreadChild for ReadLogFile
subtype の列挙してたところを、関数にくくり出して意味を持たせました。
一部のデータを解析したところ subtype は thread 内外問わず基本的に空で
**Also send to** したものが `thread_broadcast` になってるようです。
それに合わせて `isTreadChild()` のロジックを設計しています。
> refactoring subtype treatment

- templates/index.tmpl
リンクが切れていたので直しました。 (たぶんこれで直るはず。確認はしてない 😅)
> Fix link to introduction

- internal/slacklog/generator.go
> Add MAX_EMBEDDED_FILE_SIZE

- .editorconfig
> Fix css is missing from EditorConfig

- internal/slacklog/converter.go
Regexp pattern is wrong to handle title.
> fixes broken URL with title.

- .github/workflows/reviewdog.yml
reviewdogを追加するためのパッチを書きました。
#117
> [add] reviewdog

- assets/css/site.css
> Fix code-block

- internal/slacklog/generator.go
- templates/channel_per_month/index.tmpl
#124 にまつわる不具合の修正と、メンテナンス性を考慮した改良を施しました。
> fix reactions

- .editorconfig
- Makefile
and change indent size for golang
> cover target to get coverage on local

- .github/workflows/reviewdog.yml
シェルスクリプトにもreviewdogでのチェックをさせてようというPRです。
かなり不要かもしれませんが...
(PR後に初回の動作確認になるので修正が入る可能性があります、ローカルでうまくいかなかった)
> CI add 'shellcheck'

- internal/slackadapter/users.go
- main.go
- subcmd/fetchusers/fetchusers.go
I'll merge tomorrow if no one has reviewed because there is no active maintainers.
> Add `fetch-users` sub command

- internal/slacklog/message.go
An old message doesn't have `thread_ts` so the message is not added to Thread object.
But, a new reply points to the old message.  The thread that doesn't have rootMsg is created.  Therefore, nil access is occurred.
> Fix starting thread to old message

- internal/slacklog/generator.go
There are reactions that the emojis has been deleted.
> Show reactions that the emojis has been deleted

- templates/channel_per_month/attachment.tmpl
> show gyazo images

- README.md
- README_ja.md
So that anybody can read and contribute here
> Provide README in English

- static/assets/javascripts/search.js
検索時、URL にクエリパラメータが付くようになります。
クエリパラメータが付いたページを開くと、開いた直後に検索されます。ブラウザバックも可能です。
> Add query when searching

- templates/index.tmpl
> Add search link

- static/assets/javascripts/search.js
> Sort the search result by date

- internal/slacklog/generator.go
- templates/channel_per_month/attachment.tmpl
> Add link from citation in Slack to log

- templates/channel_per_month/attachment.tmpl
slacklog内のリンクは同じタブの中で開かれるように修正しました
#164に対する修正です
> Fix link format > #164
